server:
  port: 5000

spring:
  datasource:
    url: jdbc:h2:file:./numbersdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
       ddl-auto: update
    open-in-view: false
  h2:
    console:
      enabled: true